language: scala
scala:
  - 2.11.7
  - 2.11.8
  - 2.11.10
  - 2.11.11
  - 2.11.12
jdk:
  - openjdk7
  - openjdk8
sudo: false
script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - sbt ++$TRAVIS_SCALA_VERSION test